# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build_and_sync

on:
  workflow_dispatch:

jobs:
  build_and_sync:

    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.x
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # strategy:
      # matrix:
        # node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: current commit
      run: git log -n 1
    
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
        
    - run: npm install
    - run: npm run build:prod
    
    - name: copy .htaccess
      run: cp .htaccess dist/BrettSpiel/.htaccess
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avczr --delete
        path: dist/BrettSpiel/
        remote_path: ~/html/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
