name: "Build and Push Docker Image"

on:
  push:
    branches:
      - dockerize

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  
          echo Release Version: $RELEASE_VERSION
          echo Release Version from Env Variable:${{ env.RELEASE_VERSION }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build & Push Docker Containers to Docker Hub
        run:  |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tispyl-frontend:0.0.3 -f ./docker/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tispyl-frontend:0.0.3

      - name: Clean Up
        run: docker logout

