name: "Build and Push Docker Image"

on:
  push:
    branches:
      - dockerize
  create:
    tags:
      - 'v*'

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  
          echo Release Version: $RELEASE_VERSION
          echo Release Version from Env Variable:${{ env.RELEASE_VERSION }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Build & Push Docker Containers to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
         # tags: ${{ secrets.DOCKERHUB_USERNAME }}/tispyl-frontend:${{ steps.extract_tag.outputs.tag }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tispyl-frontend:0.0.4

      - name: Clean Up
        run: docker logout

