name: "Build and Push Docker Image"

on:
  push:
    branches:
      - dockerize

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version
        continue-on-error: true

      - name: Build Docker Containers
        run: |
          docker-compose build
        continue-on-error: true

      - name: Push Docker Containers to Docker Hub
        run:  |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker-compose push

      - name: Clean Up
        run: docker logout