name: "Build and Push Docker Image"

on:
  push:
    branches:
      - dockerize

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push Docker Containers to Docker Hub
        run:  |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tispyl-frontend:0.0.2 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tispyl-frontend:0.0.2

      - name: Clean Up
      - name: Clean Up
        run: docker logout